global:
  data_path: "/src/logs/rednet_dataset/{}/dataset/"
  img_size: [480, 640]
  num_classes: 40

trainer:
  max_epochs: 100
  accelerator: 'gpu'
  devices: [0, 1]
  default_root_dir: /src/logs/rednet/
  check_val_every_n_epoch: 1
  sync_batchnorm: True
  strategy: ddp

checkpoint:
  every_n_epochs: 1
  save_top_k: 20
  mode: max
  verbose: True
  save_last: True

task:
  # main model
  num_classes: "${global.num_classes}"
  model_name: rednet
  model:
    num_classes: "${global.num_classes}"
    pretrained: True
  preprocess:
    rgb_norm:
      mean: [0.493, 0.468, 0.438]
      std: [0.544, 0.521, 0.499]
    depth_norm:
      mean: 0.213
      std: 0.285
    img_size: "${global.img_size}"
  # training params
  optimizer_name: 'sgd'
  optimizer:
    lr: 2.0e-3
    momentum: 0.9
    weight_decay: 1.0e-4
  batch_size: 3
  num_workers: 3
  loss_name: 'focal'
  loss:
    weight: [0.886804, 0.812583, 0.869529, 0.938507, 0.863561, 0.962446, 0.964277, 0.907249, 1.001192, 0.908846, 0.946954, 0.952964, 0.944019, 0.997826, 1.050121, 1.118023, 0.951679, 0.884583, 1.064275, 1.118451, 1.079793, 0.991065, 0.991265, 1.054596, 1.067630, 1.093059, 1.025452, 1.048524, 1.030069, 1.061999, 0.982877, 1.003945, 1.051754, 1.180730, 1.079397, 1.143563, 0.961034, 1.007245, 1.077462, 0.924657]

  # datasets
  trainset:
    root_path: "${format: ${global.data_path}, train}"
    img_size: "${global.img_size}"
    assert_num_classes: ${global.num_classes}
    multi_scale_seg: [2, 4, 8, 16]
  valset:
    root_path: "${format: ${global.data_path}, val}"
    img_size: "${global.img_size}"
    assert_num_classes: ${global.num_classes}
  predset:
    root_path: "${format: ${global.data_path}, val}"
    img_size: "${global.img_size}"
    assert_num_classes: ${global.num_classes}
    max_length: 100
    shuffle: True

