global:
  data_path: "/src/logs/rednet_dataset/{}/dataset/"
  img_size: [480, 640]
  num_classes: 40

trainer:
  max_epochs: 500
  accelerator: 'gpu'
  devices: [0, 1, 2]
  default_root_dir: "/src/logs/acnet_nocrf/"
  check_val_every_n_epoch: 1
  sync_batchnorm: True

ddp:
  find_unused_parameters: False

checkpoint:
  every_n_epochs: 1
  save_top_k: 20
  mode: max
  verbose: True
  save_last: True

task:
  # main model
  num_classes: "${global.num_classes}"
  model_name: acnet
  model:
    num_classes: "${global.num_classes}"
    pretrained: True
  preprocess:
    rgb_norm:
      mean: [0.493, 0.468, 0.438]
      std: [0.544, 0.521, 0.499]
    depth_norm:
      mean: 0.213
      std: 0.285
    img_size: "${global.img_size}"
  # training params
  optimizer_name: 'sgd'
  optimizer:
    lr: 2.0e-3
    momentum: 0.9
    weight_decay: 1.0e-4
  decay_epochs: 20
  decay_rate: 0.8
  batch_size: 4
  num_workers: 3
  loss_name: 'focal'
  loss: {}
  #  weight: [0.003416, 0.004794, 0.022286, 0.223316, 0.019152, 0.185071, 0.192163, 0.055455, 0.398328, 0.057539, 0.267684, 0.303934, 0.125718, 0.373562, 1.935010, 2.912373, 0.147912, 0.032366, 2.462524, 2.933725, 1.592994, 0.327946, 0.658375, 1.044804, 1.302604, 1.973176, 0.625055, 0.941110, 0.679389, 1.185308, 0.279363, 0.419719, 0.994928, 7.197124, 1.582912, 4.266099, 0.179766, 0.446707, 1.533180, 0.082368]
  use_checkpoint: True
  track_iou_index: [3, 10, 11, 14, 18, 22]

  # datasets
  trainset:
    root_path: "${format: ${global.data_path}, train}"
    assert_num_classes: ${global.num_classes}
    multi_scale_seg: [2, 4, 8, 16]
    transform:
      img_size: "${global.img_size}"
      random_rate: 0.5
      random_k: 2
      crop_rate: [0.2, 0.2]
      hflip: True
      vflip: True
      move_x: 0.2
      move_y: 0.2
      rotate: 20    # degree
      shear_x: 0.2
      shear_y: 0.2
  valset:
    root_path: "${format: ${global.data_path}, val}"
    assert_num_classes: ${global.num_classes}
    transform:
      img_size: "${global.img_size}"
  predset:
    root_path: "${format: ${global.data_path}, val}"
    assert_num_classes: ${global.num_classes}
    max_length: 100
    shuffle: True
    transform:
      img_size: ${global.img_size}

